name: Test

on:
  pull_request: {}
  push:
    branches: main
    tags: '*'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.11

      - name: Install dependencies with pipenv
        run: |
          pip install pipenv
          pipenv install --deploy --dev

      - name: Check code quality
        run: |
          pipenv run isort --check-only --diff .
          pipenv run black --check .
          pipenv run flake8
          pipenv run mypy app/

      - name: Run tests with coverage
        run: pipenv run pytest --cov --cov-fail-under=80
